
?start: program

program: statement*

block: "do" statement* return_statement "end"

?statement: variable_declaration
          | function_declaration
          | struct_declaration
          | function_call

return_statement: expression

function_call: atom argument_list

argument_list: "(" (expression ("," expression)* ","?)? ")"

function_declaration: "local" NAME parameter_list "=" expression

struct_declaration: "struct" NAME parameter_list? "=" object

parameter_list: "(" (pattern ("," pattern)* ","?)? ")"

variable_declaration: "local" pattern "=" expression

?pattern: name_pattern
        | array_pattern

name_pattern: NAME

array_pattern: "{" (pattern ("," pattern)* ","?)? "}"


?expression: log_expression
           | lambda_expression
           | property_access
           | method_access
           | block


method_access: atom ":" atom argument_list

property_access: atom "." atom

lambda_expression: lambda_parameters "to" expression

?lambda_parameters: parameter_list | NAME

?log_expression: eq_expression LOG eq_expression | eq_expression

?eq_expression: rel_expression EQ rel_expression | rel_expression

?rel_expression: add_expression REL add_expression | add_expression

?add_expression: mul_expression ADD mul_expression | mul_expression

?mul_expression: unary_expression MUL unary_expression | unary_expression

?unary_expression: UNARY atom | atom

?atom: function_call
     | table
     | object
     | array
     | NUMBER
     | STRING
     | TEMPLATE_LITERAL
     | NAME

table: "{" (table_field ("," table_field)* ","?)? "}"

table_field: "[" expression "]" "=" expression

object: "{" (object_field ("," object_field)* ","?)? "}"

object_field: NAME parameter_list? "=" expression

array: "{" (expression ("," expression)* ","?)? "}"

UNARY: /not|-|\+|#/

MUL: /\*|\/|%/

ADD: /\+|-|\.\./

REL: /<|>|<=|>=/

LOG: /and|or/

EQ: /==|~=/

NAME: /[a-zA-Z_][a-zA-Z_0-9]*/

TEMPLATE_LITERAL: /`[^`]*`/

STRING: /"[^"]*"/

NUMBER: /\d+/

%ignore /\s+/
%ignore /--.*/
%ignore /--\[\[(.|\n)*\]\]/